### ISSUE TITLE
Error with caching empty json

### ISSUE THREAD

**Issue by BestFriendChris** [rails/jbuilder#242]
We ran into an error trying to cache an optional json section.

Reproduction:
```ruby
# Fake out the controller caching check in 
#   https://github.com/rails/jbuilder/blob/master/lib/jbuilder/jbuilder_template.rb#L52
require 'ostruct'
ctx = OpenStruct.new(controller: OpenStruct.new(perform_caching: true))

def build_json(ctx)
  json = JbuilderTemplate.new(ctx)
  json.cache! ["/test-cache-entry"], expired_in: 10.minutes do
    # In our code, we try to load an ActiveRecord model. If it exists, we add some json keys
  end
  json
end

# Adds to the cache the first time
build_json(ctx)
#=> {"will_be_good"=>true}

# Fails to load from the cache the second time
build_json(ctx)
TypeError: no implicit conversion of Object into Hash
        from /app/vendor/bundle/ruby/2.1.0/gems/jbuilder-2.2.6/lib/jbuilder.rb:270:in `merge'
        from /app/vendor/bundle/ruby/2.1.0/gems/jbuilder-2.2.6/lib/jbuilder.rb:270:in `_merge_values'
        from /app/vendor/bundle/ruby/2.1.0/gems/jbuilder-2.2.6/lib/jbuilder.rb:237:in `merge!'
        from /app/vendor/bundle/ruby/2.1.0/gems/jbuilder-2.2.6/lib/jbuilder/jbuilder_template.rb:57:in `cache!'
        from (irb):134
        from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/commands/console.rb:90:in `start'
        from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/commands/console.rb:9:in `start'
        from /app/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/commands.rb:62:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

It looks to me that the `Jbuilder::BLANK` object is being serialized and stored in the cache rather than the empty attributes.

**Comment by rwz** [comment]
That looks like a legit bug. Thanks for the heads up. Will look into that over the weekend.

**Comment by rwz** [comment]
Fixed in 2.2.7 :)

**Comment by BestFriendChris** [comment]
Thanks!

**Comment by DevilalDheer** [comment]
I got same issue with jbuilder (2.3.1) and ruby-2.2.2
Please reopen this issue.
