### ISSUE TITLE
CI build issue 

### ISSUE THREAD

**Issue by olleolleolle** [rails/jbuilder#479]
- AMD64
- Ruby: 2.2.10
- Gemfile: gemfiles/rails_5_2.gemfile

https://travis-ci.org/github/rails/jbuilder/jobs/663172103?utm_medium=notification&utm_source=github_status

```
# Running:

...../home/travis/build/rails/jbuilder/gemfiles/vendor/bundle/ruby/2.2.0/gems/rack-2.1.2/lib/rack/media_type.rb:18: warning: `&' interpreted as argument prefix

E

Error:

JbuilderTemplateTest#test_array_of_partials:

SyntaxError: /home/travis/build/rails/jbuilder/gemfiles/vendor/bundle/ruby/2.2.0/gems/actionpack-5.2.4.1/lib/action_dispatch/request/session.rb:96: syntax error, unexpected '.'

          id&.public_id

              ^

    /home/travis/build/rails/jbuilder/gemfiles/vendor/bundle/ruby/2.2.0/gems/actionpack-5.2.4.1/lib/action_dispatch/http/request.rb:358:in `session='

    /home/travis/build/rails/jbuilder/gemfiles/vendor/bundle/ruby/2.2.0/gems/actionpack-5.2.4.1/lib/action_controller/test_case.rb:57:in `initialize'

    /home/travis/build/rails/jbuilder/gemfiles/vendor/bundle/ruby/2.2.0/gems/actionpack-5.2.4.1/lib/action_controller/test_case.rb:46:in `new'

    /home/travis/build/rails/jbuilder/gemfiles/vendor/bundle/ruby/2.2.0/gems/actionpack-5.2.4.1/lib/action_controller/test_case.rb:46:in `create'

    /home/travis/build/rails/jbuilder/gemfiles/vendor/bundle/ruby/2.2.0/gems/actionview-5.2.4.1/lib/action_view/test_case.rb:29:in `initialize'

    /home/travis/build/rails/jbuilder/test/jbuilder_template_test.rb:299:in `new'

    /home/travis/build/rails/jbuilder/test/jbuilder_template_test.rb:299:in `build_view'

    /home/travis/build/rails/jbuilder/test/jbuilder_template_test.rb:292:in `render_without_parsing'

    /home/travis/build/rails/jbuilder/test/jbuilder_template_test.rb:288:in `render'

    /home/travis/build/rails/jbuilder/test/jbuilder_template_test.rb:101:in `block in <class:JbuilderTemplateTest>'

bin/rails test home/travis/build/rails/jbuilder/test/jbuilder_template_test.rb:100
```

**Comment by rafaelfranca** [comment]
Update the  gemfiles/rails_5_2.gemfile to point to 5.2 stable and the build will be fixed.

**Comment by olleolleolle** [comment]
The 5-2-stable branch: contains a gemspec which  says ">= 2.2.0" required_ruby_version. Its last commit is "prepare for 5.2.4.1 release". Seems like safe navigation (a 2.3+ feature) has crept in without a bump to `required_ruby_version` in the gemspec..

**Comment by olleolleolle** [comment]
I was hasty in my reading. A PR which does what was suggested works. Thanks!
