### ISSUE TITLE
ruby 3.4.0dev deprecates OpenStruct

### ISSUE THREAD

**Issue by yahonda** [rails/jbuilder#561]
jbuilder has OpenStruct that will be deprecated in Ruby 3.4.0dev.
https://bugs.ruby-lang.org/issues/20309

- foo.rb
```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "jbuilder"
end
p RUBY_VERSION
```

### Expected behavior
It should not show any warnings as executed against Ruby 3.3.0.

```ruby
$ ruby foo.rb
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
"3.3.0"
```

### Actual behavior
It raises `warning: ostruct was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.5.0. Add ostruct to your Gemfile or gemspec.` warning.

```ruby
$ ruby foo.rb
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
/home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.4.0+0/gems/jbuilder-2.11.5/lib/jbuilder.rb:7: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.5.0. Add ostruct to your Gemfile or gemspec.
"3.4.0"
```

**Comment by yahonda** [comment]
Here are the lines OpenStruct is used.

https://github.com/rails/jbuilder/blob/387561395daf471f05287fc67d28e0a296988f57/lib/jbuilder.rb#L7

https://github.com/rails/jbuilder/blob/387561395daf471f05287fc67d28e0a296988f57/lib/jbuilder.rb#L31

**Comment by yahonda** [comment]
Here are the sample repository to show which gem actually requires `ostruct`.

```ruby
$ git clone https://github.com/yahonda/diag391
$ cd diag391/
$ bundle install
$ bin/rails dev
```

```ruby
$ ruby -v
ruby 3.4.0dev (2024-04-09T16:29:01Z master 0107954f25) [x86_64-linux]
$ bin/rails dev
"/home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.4.0+0/gems/jbuilder-2.11.5/lib/jbuilder.rb:7:in '<top (required)>'"
/home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.4.0+0/bundler/gems/zeitwerk-dd07889c9c40/lib/zeitwerk/kernel.rb:35: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.5.0. Add ostruct to your Gemfile or gemspec.
"/home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.4.0+0/gems/rack-3.0.10/lib/rack/show_exceptions.rb:3:in '<top (required)>'"
Commands:
  bin/rails dev:cache           # Toggle development mode caching on/off
  bin/rails dev:help [COMMAND]  # Describe available commands or one specific command
```
